export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_ADVERTISEMENT = 'CREATE_ADVERTISEMENT';
export const FETCH_ADVERTISEMENTS = 'FETCH_ADVERTISEMENTS';
export const FETCH_ADVERTISEMENT = 'FETCH_ADVERTISEMENT';
export const DELETE_ADVERTISEMENT = 'DELETE_ADVERTISEMENT';
export const EDIT_ADVERTISEMENT = 'EDIT_ADVERTISEMENT';
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';